project:
  type: website
  output-dir: docs
  
website:
  title: "Visiting NCSU"
  reader-mode: false
  search: true
  navbar:
    right:
      - text: About
        href: about.qmd
      - icon: mastodon
        aria-label: mastodon
        href: https://fosstodon.org/@VeronicaAndreo
      - icon: github
        aria-label: github
        href: https://github.com/veroandreo
    left:
      - text: "Lecture"
        href: introduction.qmd
      - text: "Studio"
        href: studio_index.qmd
      - menu: 
          - href: notebook_intro.qmd
          - href: notebook_ex_rs_grass.qmd
          - href: notebook_ex_sdm_r.qmd
  page-footer:
    center: 
       - text: "&#169; 2023 Verónica Andreo, <span xmlns:cc=\"http://creativecommons.org/ns#\" xmlns:dct=\"http://purl.org/dc/terms/\">licensed under <a href=\"http://creativecommons.org/licenses/by/4.0/?ref=chooser-v1\" target=\"_blank\" rel=\"license noopener noreferrer\" style=\"display:inline-block;\">CC BY 4.0<img style=\"height:18px!important;margin-left:3px;vertical-align:text-bottom;\" src=\"https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1\"><img style=\"height:18px!important;margin-left:3px;vertical-align:text-bottom;\" src=\"https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1\"></a></p>"

execute:
  freeze: auto  # re-render only when source changes
  warning: false
  
  
bibliography: references.bib
csl: american-statistical-association.csl
citations-hover: true
knitr:
  opts_chunk: 
    #collapse: true
    comment: "##"
    results: "hold"

format: 
  html:
    theme: 
      light: flatly
      dark: darkly    
    code-link: true
    code-fold: true
    code-tools: 
      toggle: true
      source: false
    self-contained: true
    toc: true
    toc-location: right
    toc-title: Contents
    #title-block-categories: true
    highlight-style: arrow
    #title-block-banner: "#546e7a"
    #title-block-banner-color: "white"
    code-block-bg: true
    code-block-background: true
    code-block-border-left: true
    fontsize: 12pt
    code-overflow: "wrap"
    #code-overflow: "scroll"
    code-line-numbers: true

    